# Generated by Django 3.2.8 on 2021-10-21 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='Класса')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО преподавателя')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(max_length=150, verbose_name='Дата')),
                ('time', models.CharField(max_length=150, verbose_name='ФИО преподавателя')),
                ('discipline', models.CharField(max_length=250, verbose_name='ФИО преподавателя')),
                ('teacher', models.CharField(max_length=150, verbose_name='ФИО преподавателя')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teachers')),
            ],
        ),
    ]
