# Generated by Django 3.2.8 on 2021-10-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Список классов', 'verbose_name_plural': 'Список классов'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Рассписание уроков', 'verbose_name_plural': 'Рассписание уроков'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Список преподавателей', 'verbose_name_plural': 'Список преподавателей'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='discipline',
            field=models.CharField(max_length=250, verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(max_length=150, verbose_name='Время'),
        ),
    ]
