# Generated by Django 3.2.8 on 2021-10-26 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211025_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=3, unique=True, verbose_name='Класса'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.groups', to_field='name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teachers', to_field='fio'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='fio',
            field=models.CharField(max_length=150, unique=True, verbose_name='ФИО преподавателя'),
        ),
    ]
