# Generated by Django 3.2.8 on 2021-10-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211027_0121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='GroupsSchool',
        ),
    ]
