# Generated by Django 3.2.8 on 2021-10-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_schedule_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subgroup',
            field=models.IntegerField(default=None, null=True, verbose_name='Подгруппа'),
        ),
    ]
